---
# tasks file for openshift-master-cfg
- name: Copy file /etc/origin/master/master-config.yaml
  copy:
    src=master-config.yaml
    dest=/etc/origin/master/master-config.yaml

- name: Configure /etc/docker/daemon.json
  template:
    src: daemon.j2
    dest: /etc/docker/daemon.json
  notify:
    - service docker reload
